/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eurobiznes;

/**
 *
 * @author Lenovo
 */
public class ActOfOwnershipNetworks extends ActOfOwnership 
{

    /**
     * Creates new form ActOfOwnershipNetworks
     */
    public ActOfOwnershipNetworks() 
    {
        initComponents();
    }
    public ActOfOwnershipNetworks(String number, String title, String state, String city,String PriceBuyText,String PriceBuy,String Info,String MortageText,String MortagePrice) 
    {
        super(number,title,state,city);
        initComponents();
        this.PriceBuyText.setText(PriceBuyText);
        this.PriceBuy.setText(PriceBuy);
        this.Info.setText(Info);
        this.MortgageText.setText(MortageText);
        this.MortgagePrice.setText(MortagePrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                         
    private void initComponents() {

        PriceBuyText = new javax.swing.JLabel();
        PriceBuy = new javax.swing.JLabel();
        MortgageText = new javax.swing.JLabel();
        MortgagePrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 525));

        PriceBuyText.setText("jLabel1");

        PriceBuy.setText("jLabel2");

        MortgageText.setText("jLabel3");

        MortgagePrice.setText("jLabel4");

        Info.setEditable(false);
        Info.setColumns(20);
        Info.setRows(5);
        Info.setMaximumSize(new java.awt.Dimension(214, 100));
        jScrollPane1.setViewportView(Info);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PriceBuyText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(PriceBuy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MortgageText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MortgagePrice)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceBuyText)
                    .addComponent(PriceBuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MortgageText)
                    .addComponent(MortgagePrice))
                .addContainerGap())
        );

        pack();
    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipNetworks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipNetworks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipNetworks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipNetworks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActOfOwnershipNetworks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Info;
    private javax.swing.JLabel MortgagePrice;
    private javax.swing.JLabel MortgageText;
    private javax.swing.JLabel PriceBuy;
    private javax.swing.JLabel PriceBuyText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
