/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eurobiznes;

/**
 *
 * @author Lenovo
 */
public class ActOfOwnershipRailway extends ActOfOwnership 
{

    /**
     * Creates new form ActOfOwnershipRailway
     */
    public ActOfOwnershipRailway() 
    {
        initComponents();
    }

    public ActOfOwnershipRailway(String number, String title, String state, String city,String PriceBuyText,String PriceBuy,String Info,String Info1,String Price1,String Info2,String Price2,String Info3,String Price3,String Info4,String Price4,String MortgageText,String MortgagePrice) 
    {
        super(number,title,state,city);
        initComponents();
        this.PriceBuyText.setText(PriceBuyText);
        this.PriceBuy.setText(PriceBuy);
        this.Info.setText(Info);
        this.Info1.setText(Info1);
        this.Price1.setText(Price1);
        this.Info2.setText(Info2);
        this.Price2.setText(Price2);
        this.Info3.setText(Info3);
        this.Price3.setText(Price3);
        this.Info4.setText(Info4);
        this.Price4.setText(Price4);
        this.MortgageText.setText(MortgageText);
        this.MortgagePrice.setText(MortgagePrice);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PriceBuyText = new javax.swing.JLabel();
        PriceBuy = new javax.swing.JLabel();
        Info1 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();
        MortgageText = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        MortgagePrice = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(340, 525));

        PriceBuyText.setText("jLabel1");

        PriceBuy.setText("jLabel2");

        Info1.setText("jLabel3");

        Info2.setText("jLabel4");

        Info3.setText("jLabel5");

        Info4.setText("jLabel6");

        MortgageText.setText("jLabel7");

        Price1.setText("jLabel8");

        Price2.setText("jLabel9");

        Price3.setText("jLabel10");

        Price4.setText("jLabel11");

        MortgagePrice.setText("jLabel12");

        Info.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MortgageText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(MortgagePrice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PriceBuyText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PriceBuy)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceBuyText)
                    .addComponent(PriceBuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Info)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info1)
                    .addComponent(Price1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info2)
                    .addComponent(Price2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info3)
                    .addComponent(Price3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info4)
                    .addComponent(Price4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MortgageText)
                    .addComponent(MortgagePrice))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipRailway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipRailway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipRailway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActOfOwnershipRailway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActOfOwnershipRailway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JLabel Info4;
    private javax.swing.JLabel MortgagePrice;
    private javax.swing.JLabel MortgageText;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JLabel PriceBuy;
    private javax.swing.JLabel PriceBuyText;
    // End of variables declaration//GEN-END:variables
}
